project_id = "xwbyyzvtwcsehmprsbvg"

[functions.create-user-profile]
verify_jwt = false

[functions.geocode-address]
verify_jwt = true

[functions.gerar-ordem-servico]
verify_jwt = true

[functions.send-calendar-invite]
verify_jwt = true