project_id = "xwbyyzvtwcsehmprsbvg"

[functions.create-user-profile]
verify_jwt = true

[functions.geocode-address]
verify_jwt = true

[functions.process-pending-geocoding]
verify_jwt = false

[functions.gerar-ordem-servico]
verify_jwt = true

[functions.send-calendar-invite]
verify_jwt = true

[functions.send-os-reminders]
verify_jwt = false

[functions.confirm-presence]
verify_jwt = false

[functions.optimize-route-osrm]
verify_jwt = true

[functions.test-resend]
verify_jwt = false
